import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";
import ReactQueryProvider from "./components/reactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({ subsets: ["latin"], display: "swap", weight: ["300", "400", "500", "600", "700"], variable: '--font-quicksand' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={quicksand.variable}>
      <body>
        <ReactQueryProvider>
          <div className="container">
            <Header />
            <main>
              {children}
            </main>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
